### ISSUE TITLE
wrong config.vm.box_url

### ISSUE THREAD

**Issue by bodote** [lukaspustina/docker-demo#4]
add
> *config.vm.box = "phusion/ubuntu-14.04-amd64"*

and delete line:
>*config.vm.box_url = ....*

because the 
>*config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/trusty/20140904/trusty-server-cloudimg-amd64-vagrant-disk1.box"*

is not longer available there, and 
>*http://cloud-images.ubuntu.com/vagrant/trusty/20150116.1/trusty-server-cloudimg-amd64-vagrant-vagrant-disk1.box* 

does not really run docker without errors, so  
>*config.vm.box = "phusion/ubuntu-14.04-amd64"*

( which takes the image from the vagrant image-repository ) seems to do better

**Comment by lukaspustina** [comment]
Thanks for your bug ticket. I had a cold and wasn't able to respond earlier. I hope the demo works for again.
