### ISSUE TITLE
make run does not work

### ISSUE THREAD

**Issue by bodote** [lukaspustina/docker-demo#5]
whereas "make build" did work as expected the "make run" does not:
root@docker-demo:/vagrant# make run
+++ Starting containers +++
2015/01/16 15:09:49 Error response from daemon: Cannot start container 86782c2f6
6090b974f676c7c3b7b46bb51e8e8745e68d2f8a46e9e6c39c3c463: no such file or directo
ry
86782c2f6609        lukaspustina/docker_demo_webserver:latest   "/opt/webserver/
run.   1 seconds ago                                               webserver-1

2015/01/16 15:09:49 Error response from daemon: Cannot start container 05ff8d747
3b20126f122666aeea14f5ea7b884a346c423367661af5d41b35715: no such file or directo
ry
05ff8d7473b2        lukaspustina/docker_demo_webserver:latest   "/opt/webserver/
run.   Less than a second ago                                           webserve
r-2
root@docker-demo:/vagrant#

**Comment by bodote** [comment]
with 
>*config.vm.box = "phusion/ubuntu-14.04-amd64"*
and deleting 
>config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/trusty/20140904
>/trusty-server-cloudimg-amd64-vagrant-disk1.box"
then try adding these lines to the *Vagrantfile*: 

>config.vm.provision "shell", inline: <<-SHELL
>#latest docker:
>[ -e /usr/lib/apt/methods/https ] || {
>   sudo apt-get update
>    sudo apt-get install apt-transport-https
>  }
>  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
>  sudo sh -c "echo deb https://get.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
>  sudo apt-get update
>  sudo apt-get install -y lxc-docker
>  SHELL

**Comment by lukaspustina** [comment]
Also fixed by aa37b25
